language: cpp

compiler:
    - clang
    - gcc

notifications:
    email:
        on_failure: always
        on_success: change


before_install:
    - sudo apt-get install cmake
install:
    - sudo apt-get install libprotobuf-dev protobuf-compiler libboost-dev libgtest-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - make
script:
    - make test
