language: cpp

compiler:
    - clang
    - gcc

notifications:
    email:
        on_failure: always
        on_success: change


before_install:
    - sudo apt-get update
    - sudo apt-get install cmake libgtest-dev valgrind
install:
    - sudo apt-get install libprotobuf-dev protobuf-compiler libboost-all-dev

before_script:
    - mkdir build
    - cd build
    - UNIT_TEST_VALGRIND=1 cmake .. -DCMAKE_BUILD_TYPE=debug
    - make VERBOSE=1
script:
    - make test
