language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install cmake
install:
    - sudo apt-get install libprotobuf-dev protobuf-compiler

before_script:
    - mkdir build
    - 'cd build &&  cmake .. && make'
script:
    - 'cd build && make test'
